### ISSUE TITLE
Новая неделя

### ISSUE THREAD

**Issue by YerldSHO** [YerldSHO/Hack#3]
Ожидаем ТЗ!

ЛК только для оргов, участникам присылают письмо на почту.
Как редактировать модель есть в телеге(С примером).

**Основные задачи:** 
Подготовить дизайн для готовой структуры(В телеге есть инфа) _Верстать ЛК не обязатлеьно!!_. 
Разобраться с работой  модели и админки в джанго.
Оформить красивую модель в админке.
Оформить ЛК для оргов (в админке) и найти способ реализации отправки письма(соответственно сделать рассылку на почту).

Админку храним в sqllite3(оригинальная база данных джанго).

Предыдущие задания выполнены!
Пока ожидаем изменения задания (перекур с печенньками).
15.06.22

**Comment by Nezimov** [comment]
Дизайн для структуры готов. Осталось дождаться оценки и приступить к верстке
